### ISSUE TITLE
Installed this on Joomla 2.5.28 and it's not working

### ISSUE THREAD

**Issue by lifelightweb** [vdespa/PHPExcel-Joomla-Library#2]
When I make the call to open the "Excel5" file, it tries to open as .htm and the excel format is corrupted.  This is the same result as having the regular PHPExcel library installed.  I don't see that anything functionality-wise has changed.  Please advise what I need to do to get the Excel file to open without being corrupted.

**Comment by lifelightweb** [comment]
So to write the file to the server it works just fine with the $objWriter->save("file.xls");  however, to implement the methods to save and prompt the user to download, it does not work.  Seems to me this is where the Joomla conflict arises.  It keeps trying to open what it thinks is an html file instead of the xls file.  

Code that works to write file to server:
    $objWriter = new PHPExcel_Writer_Excel5($objPHPExcel);
    $objWriter->save($filename);

Code that does not work to prompt user to download file just created:
  // Redirect output to a client’s web browser (Excel5)
    header("Pragma: public");
    header("Expires: 0");
    header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
    header("Content-Type: application/force-download");
    header("Content-Type: application/octet-stream");
    header("Content-Type: application/download");
    header("Content-Disposition: attachment;filename=".$filename);
    header("Content-Transfer-Encoding: binary ");

    $objWriter = new PHPExcel_Writer_Excel5($objPHPExcel);
    $objWriter->save('php://output');

Is there a way to make this work in Joomla 2.5.x?

**Comment by vdespa** [comment]
Hi, I am not sure about the content in which you are calling the library. It seems that you are not asking Joomla to give you a raw output. There should not be any HTML. Try to append format=raw to your request or to search more on the topic "Joomla raw output".

Hope this helps.
